name = "my-worker-name"  # Replace with your desired worker name
compatibility_date = "2024-10-20"


[vars]

DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqd3RfaWQiOjEsInNlY3VyZV9rZXkiOiJza19RbVNFX0FiQ050dTg1Tk41aGpURmQiLCJhcGlfa2V5IjoiMDFLNlQ0MlYxOTk1NFBQUVZKSEYwMFFXM1YiLCJ0ZW5hbnRfaWQiOiJkNjNjOTliZGYxZWU5NzY0YWQ2N2JkNjcyMDNjMGVjMjdkNGNmZDkwYTc3NmM3MjU0MzZjNWY2YTdkYzcxMjNhIiwiaW50ZXJuYWxfc2VjcmV0IjoiZGFkMWEyOGItZWE1NC00N2MxLThkOTktOWJjNWU4NzgzM2Y1In0.7eCU4jAvJ0OR2Nho7aHIeNfWrwb_hLc51fyqfRr_STI"

JWT_SECRET = "your-secret-key-here"