name = "my-worker-name"  # Replace with your desired worker name
compatibility_date = "2024-10-20"


[vars]

DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqd3RfaWQiOjEsInNlY3VyZV9rZXkiOiJza193YkYzTXdmZkJzZkRib3N5aDNLbG0iLCJhcGlfa2V5IjoiMDFLNlQxMzNEVzQwSk4xREtEWTk3RVFNMVciLCJ0ZW5hbnRfaWQiOiI2YWQ1YjE5MmEyODM3ZTk5ZDc5MzZjMzkyYTVmMzBhY2IzMGNkMDRkMjVjZDQzZTBmNjUyODhkNTgyNTUwMzY3IiwiaW50ZXJuYWxfc2VjcmV0IjoiMzNkODNmODUtMzM0Yy00NjI4LWI5MDgtOGIwNTMzZGFmOThmIn0.TjQLWT0BlS1K1frI24QU54lTbbDYH2GYRISmSP6oq2U"

JWT_SECRET = "your-secret-key-here"