name = "my-worker-name"  # Replace with your desired worker name
compatibility_date = "2024-10-20"


[vars]


DATABASE_URL="prisma+postgres://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMDFKWFpHWVdQS1kySjFLRlcwMkhXODZSVFMiLCJ0ZW5hbnRfaWQiOiI2YWQ1YjE5MmEyODM3ZTk5ZDc5MzZjMzkyYTVmMzBhY2IzMGNkMDRkMjVjZDQzZTBmNjUyODhkNTgyNTUwMzY3IiwiaW50ZXJuYWxfc2VjcmV0IjoiMzNkODNmODUtMzM0Yy00NjI4LWI5MDgtOGIwNTMzZGFmOThmIn0.NLvrAFIuWRvXEju3js-fWUgw2RFSKFLmapUjqIJuqJ0"

JWT_SECRET = "your-secret-key-here"